algoritmo "PORTUGOL1"
//disciplina : [Algoritmos e programação estruturada]
//Professor : Cícero Odilio Cruz
//Descrição : Exponenciação
//Autor: Joaão Vittor Moreira de Oliveira
var
   n1, n2, s : inteiro
inicio
      escreva("Insita um numero: ")
      leia (n1)
      escreva("Insira outro numero: ")
      leia (n2)
      s <- n1 + n2
      escreva("A soma de ", n1, " com ", n2, " é igual á ", s)
fimalgoritmo
