algoritmo "PORTUGO10"
//disciplina : [Algoritmos e programação estruturada]
//Professor : Cícero Odilio Cruz
//Descrição : Exponenciação
//Autor: João Vittor Moreira de Oliveira
//Data atual : 08/09/2020
var
   compra, prestacoes: real
inicio
      escreva("Insira o valor total da compra R$")
      leia(compra)
      prestacoes <- compra / 5
      escreva("O valor parcelado será de R$", prestacoes, " em 5 vezes sem juros")
fimalgoritmo
