algoritmo "PORTUGOL13"
//disciplina : [Algoritmos e programação estruturada]
//Professor : Cícero Odilio Cruz
//Descrição : Exponenciação
//Autor: João Vittor Moreira de Oliveira
//Data atual : 08/09/2020
var
   n: inteiro
inicio
      escreva("Insira um numero: ")
      leia(n)
      se n > 10 entao
         escreval("---ANALISE---")
         escreva("Este numero é maior que 10")
      fimse
fimalgoritmo
