algoritmo "PORTUGOL15"
//disciplina : [Algoritmos e programação estruturada]
//Professor : Cícero Odilio Cruz
//Descrição : Exponenciação
//Autor: João Vittor Moreira de Oliveira
//Data atual : 08/09/2020
var
   n1 : inteiro
inicio
      escreva("Insira um numero: ")
      leia(n1)
      se (n1 > 100) e (n1 < 200) ENTAO
         escreva("O numero ", n1, " esta entre 100 e 200")
      senao
           escreva("O numero", n1, " não esta entre 100 e 200")
      fimse
fimalgoritmo
