algoritmo "PORTUGOL3"
//disciplina : [Algoritmos e programação estruturada]
//Professor : Cícero Odilio Cruz
//Descrição : Exponenciação
//Autor: João Vittor Moreira de Oliveira
//Data atual : 08/09/2020
var
   ctot, kmtot, media : real
inicio
      escreva("Insira a distância total percorrida: ")
      leia(kmtot)
      escreva("Insira o total de combustivel gasto: ")
      leia(ctot)
      media <- kmtot / ctot
      escreva("O cunsumo médio do seu automóvel é ", media)
      
fimalgoritmo
