algoritmo "PORTUGOL7"
//disciplina : [Algoritmos e programação estruturada]
//Professor : Cícero Odilio Cruz
//Descrição : Exponenciação
//Autor: João Vittor Moreira de Oliveira
//Data atual : 08/09/2020
var
   tempc, tempf: real
inicio
      escreva("Insira a temperatura para ser convertida(Cº): ")
      leia(tempc)
      tempf <- (9 * tempc + 160) / 5
      escreva("Temperatura em Fahrenheit: ", tempf)
fimalgoritmo
