algoritmo "POTRUGOL8"
//disciplina : [Algoritmos e programação estruturada]
//Professor : Cícero Odilio Cruz
//Descrição : Exponenciação
//Autor: João Vittor Moreira de Oliveira
//Data atual : 08/09/2020
var
   dolar, reais: real
inicio
      escreva("Insira um valor em dolar: U$")
      leia(dolar)
      reais <- dolar * 5.29
      escreva("O valor U$", dolar, " é igual a R$", reais)
fimalgoritmo
