algoritmo "PORTUGOL9"
//disciplina : [Algoritmos e programação estruturada]
//Professor : Cícero Odilio Cruz
//Descrição : Exponenciação
//Autor: João Vittor Moreira de Oliveira
//Data atual : 08/09/2020
var
   dep, rend : real
inicio
      escreva("Insira o valor que foi depositado: ")
      leia(dep)
      rend <- (dep * 0.70) + dep
      escreva("O valor no final do mes será de R$", rend)
fimalgoritmo
